### ISSUE TITLE
No module named 'geotorch.models'

### ISSUE THREAD

**Issue by Tensor10** [DataSystemsLab/GeoTorch#2]
No module named 'geotorch.models' how to solve that error

**Comment by kanchanchy** [comment]
Could you please give details on when you are getting this error? How are you using it in your code?
If you use geotorch without installing it, your working file should be under the root directory of the repository where the geotorch package or subdirectory resides.  If you install geotorch, then you can place your code/working file anywhere. We will be releasing detailed installation instructions within the next few days. We appreciate your patience.

**Comment by kanchanchy** [comment]
Clone or download the repository again. Then, under the root directory of the repository (where the setup.py file is located), run python setup.py install or python3 setup.py install. It will install GeoTorch on your local computer if all dependencies are installed. After that, you will be able to import any module from GeoTorch.

**Comment by Tensor10** [comment]
[image: image.png][image: image.png]
i have install these but still have this problem

**Comment by kanchanchy** [comment]
The image that you attached cannot be viewed. Could you please share a very small part of your code so that we can understand how you are using geotorch module?

**Comment by Tensor10** [comment]
i am using by spyder python terminal , and running your code , can i have
jupyter notebook for the geotorch

**Comment by kanchanchy** [comment]
Yes, you can use GeoTorch with Jupiter notebook, but GeoTorch should be installed properly before you open Jupyter notebook.

**Comment by Tensor10** [comment]
can i have conda-forge command for installing the geopytroch for proper
installation?

**Comment by kanchanchy** [comment]
Hi @Tensor10, there was an issue with the setup.py file for which it was not getting installed properly. The issue has been resolved. You can try the approach previously suggested:
1. Download the repository
2. 2. Run python setup.py install or python3 setup.py install under the root directory
