### ISSUE TITLE
ModuleNotFoundError: No module named 'geotorch.models'

### ISSUE THREAD

**Issue by surendra1234sharma** [DataSystemsLab/GeoTorch#4]
When I am running following code
from geotorch.models.raster import DeepSatV2
I am getting ModuleNotFoundError
ModuleNotFoundError: No module named 'geotorch.models'

**Comment by kanchanchy** [comment]
Hi @surendra1234sharma, I was wondering whether you installed geotorch perfectly. We tested it on multiple devices and didn't face this issue.

**Comment by surendra1234sharma** [comment]
Yes, the issue has been resolved. Earlier, I installed different geotorch library from GitHub.
I installed it from the following link and it is working.
[GeoTorch](https://github.com/DataSystemsLab/GeoTorch)
